apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: vsurzhyk-aws-managed-dev-1
  namespace: dev
spec:
  template: aws-standalone-cp-0-2-0
  credential: aws-cluster-identity-cred
  config:
    clusterLabels:
      env: dev
    controlPlaneNumber: 3
    workersNumber: 1
    region: eu-west-2
    controlPlane:
      instanceType: t3.medium
    worker:
      instanceType: t3.medium
